spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://master_postgres:5432/postgres
    username: user
    password: password
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  data:
    redis:
      port: 6379
      host: master_redis

  kafka:
    producer:
      bootstrap-servers: host.docker.internal:9092,host.docker.internal:9094,host.docker.internal:9096
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      retries: 3
      acks: all
      properties:
        delivery.timeout.ms: 120000
        request.timeout.ms: 30000
        enable.idempotence: true
        max.in.flight.requests.per.connection: 5

server:
  port: 8080

logging:
  level:
    root: info