spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/postgres
    username: user
    password: password
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  data:
    redis:
      port: 6379
      host: localhost
      ttl:
        event: 1800
        user: 1800

  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: score-trackers
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      enable-auto-commit: false
      properties:
        spring.json.trusted.packages: '*'
    producer:
      acks: all
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    retry:
      attempts: 3
      backoff: 3000

topics:
  user-score-changed: user.score.changed
  user-score-changed-dlt: user.score.changed.dlt

score:
  rules:
    default-values:
      COMPLETE_GOAL: 10
    role-values:
      COMPLETE_EVENT:
        OWNER: 5
        ATTENDEE: 2

server:
  port: 8080

logging:
  level:
    root: info

services:
  project-service:
    host: localhost
    port: 8082

  payment-service:
    host: localhost
    port: 9080

  dice-bear:
    url: https://api.dicebear.com
    version: 9.x

  s3:
    host: localhost
    post: 9000
    accessKey: user
    secretKey: password
    bucketName: corpbucket

jobs:
  promotion:
    close:
      view:
        cron: "*/15 * * * * *"
          # Каждые 15 секунд
      time:
        cron: "*/15 * * * * *"
        # Каждые 15 секунд

