spring:
  application:
    name: User Service
    version: 1.0.0
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  data:
    redis:
      port: 6379
      host: localhost

server:
  port: 8080

logging:
  level:
    root: info

project-service:
  host: localhost
  port: 8082

payment-service:
  host: localhost
  port: 9080

user:
  password:
    min:
      length: 6

goal:
  max-active-goals: 2

cloud:
  aws:
    region:
      static: default
    stack:
      auto: false
    credentials:
      access-key: user
      secret-key: password
    s3:
      bucketName: bucket
      endpoint: http://localhost:9000

dicebear:
  base-url: https://api.dicebear.com/7.x
  default-style: adventurer