package school.faang.user_service.mapper.country;

import org.springframework.stereotype.Component;

import java.util.HashMap;
import java.util.Map;

@Component
public class CountryMapper {
    private static final Map<String, String> COUNTRY_MAP = new HashMap<>();

    static
    {
        COUNTRY_MAP.put("AFG", "Afghanistan");
        COUNTRY_MAP.put("ALB", "Albania");
        COUNTRY_MAP.put("DZA", "Algeria");
        COUNTRY_MAP.put("AND", "Andorra");
        COUNTRY_MAP.put("AGO", "Angola");
        COUNTRY_MAP.put("ATG", "Antigua and Barbuda");
        COUNTRY_MAP.put("ARG", "Argentina");
        COUNTRY_MAP.put("ARM", "Armenia");
        COUNTRY_MAP.put("AUS", "Australia");
        COUNTRY_MAP.put("AUT", "Austria");
        COUNTRY_MAP.put("AZE", "Azerbaijan");
        COUNTRY_MAP.put("BHS", "Bahamas");
        COUNTRY_MAP.put("BHR", "Bahrain");
        COUNTRY_MAP.put("BGD", "Bangladesh");
        COUNTRY_MAP.put("BRB", "Barbados");
        COUNTRY_MAP.put("BLR", "Belarus");
        COUNTRY_MAP.put("BEL", "Belgium");
        COUNTRY_MAP.put("BLZ", "Belize");
        COUNTRY_MAP.put("BEN", "Benin");
        COUNTRY_MAP.put("BTN", "Bhutan");
        COUNTRY_MAP.put("BOL", "Bolivia");
        COUNTRY_MAP.put("BIH", "Bosnia and Herzegovina");
        COUNTRY_MAP.put("BWA", "Botswana");
        COUNTRY_MAP.put("BRA", "Brazil");
        COUNTRY_MAP.put("BRN", "Brunei");
        COUNTRY_MAP.put("BGR", "Bulgaria");
        COUNTRY_MAP.put("BFA", "Burkina Faso");
        COUNTRY_MAP.put("BDI", "Burundi");
        COUNTRY_MAP.put("CPV", "Cabo Verde");
        COUNTRY_MAP.put("KHM", "Cambodia");
        COUNTRY_MAP.put("CMR", "Cameroon");
        COUNTRY_MAP.put("CAN", "Canada");
        COUNTRY_MAP.put("CAF", "Central African Republic");
        COUNTRY_MAP.put("TCD", "Chad");
        COUNTRY_MAP.put("CHL", "Chile");
        COUNTRY_MAP.put("CHN", "China");
        COUNTRY_MAP.put("COL", "Colombia");
        COUNTRY_MAP.put("COM", "Comoros");
        COUNTRY_MAP.put("COG", "Congo");
        COUNTRY_MAP.put("CRI", "Costa Rica");
        COUNTRY_MAP.put("HRV", "Croatia");
        COUNTRY_MAP.put("CUB", "Cuba");
        COUNTRY_MAP.put("CYP", "Cyprus");
        COUNTRY_MAP.put("CZE", "Czech Republic");
        COUNTRY_MAP.put("DNK", "Denmark");
        COUNTRY_MAP.put("DJI", "Djibouti");
        COUNTRY_MAP.put("DMA", "Dominica");
        COUNTRY_MAP.put("DOM", "Dominican Republic");
        COUNTRY_MAP.put("ECU", "Ecuador");
        COUNTRY_MAP.put("EGY", "Egypt");
        COUNTRY_MAP.put("SLV", "El Salvador");
        COUNTRY_MAP.put("GNQ", "Equatorial Guinea");
        COUNTRY_MAP.put("ERI", "Eritrea");
        COUNTRY_MAP.put("EST", "Estonia");
        COUNTRY_MAP.put("SWZ", "Eswatini");
        COUNTRY_MAP.put("ETH", "Ethiopia");
        COUNTRY_MAP.put("FJI", "Fiji");
        COUNTRY_MAP.put("FIN", "Finland");
        COUNTRY_MAP.put("FRA", "France");
        COUNTRY_MAP.put("GAB", "Gabon");
        COUNTRY_MAP.put("GMB", "Gambia");
        COUNTRY_MAP.put("GEO", "Georgia");
        COUNTRY_MAP.put("DEU", "Germany");
        COUNTRY_MAP.put("GHA", "Ghana");
        COUNTRY_MAP.put("GRC", "Greece");
        COUNTRY_MAP.put("GRD", "Grenada");
        COUNTRY_MAP.put("GTM", "Guatemala");
        COUNTRY_MAP.put("GIN", "Guinea");
        COUNTRY_MAP.put("GNB", "Guinea-Bissau");
        COUNTRY_MAP.put("GUY", "Guyana");
        COUNTRY_MAP.put("HTI", "Haiti");
        COUNTRY_MAP.put("HND", "Honduras");
        COUNTRY_MAP.put("HUN", "Hungary");
        COUNTRY_MAP.put("ISL", "Iceland");
        COUNTRY_MAP.put("IND", "India");
        COUNTRY_MAP.put("IDN", "Indonesia");
        COUNTRY_MAP.put("IRN", "Iran");
        COUNTRY_MAP.put("IRQ", "Iraq");
        COUNTRY_MAP.put("IRL", "Ireland");
        COUNTRY_MAP.put("ISR", "Israel");
        COUNTRY_MAP.put("ITA", "Italy");
        COUNTRY_MAP.put("JAM", "Jamaica");
        COUNTRY_MAP.put("JPN", "Japan");
        COUNTRY_MAP.put("JOR", "Jordan");
        COUNTRY_MAP.put("KAZ", "Kazakhstan");
        COUNTRY_MAP.put("KEN", "Kenya");
        COUNTRY_MAP.put("KIR", "Kiribati");
        COUNTRY_MAP.put("PRK", "North Korea");
        COUNTRY_MAP.put("KOR", "South Korea");
        COUNTRY_MAP.put("KWT", "Kuwait");
        COUNTRY_MAP.put("KGZ", "Kyrgyzstan");
        COUNTRY_MAP.put("LAO", "Laos");
        COUNTRY_MAP.put("LVA", "Latvia");
        COUNTRY_MAP.put("LBN", "Lebanon");
        COUNTRY_MAP.put("LSO", "Lesotho");
        COUNTRY_MAP.put("LBR", "Liberia");
        COUNTRY_MAP.put("LBY", "Libya");
        COUNTRY_MAP.put("LIE", "Liechtenstein");
        COUNTRY_MAP.put("LTU", "Lithuania");
        COUNTRY_MAP.put("LUX", "Luxembourg");
        COUNTRY_MAP.put("MDG", "Madagascar");
        COUNTRY_MAP.put("MWI", "Malawi");
        COUNTRY_MAP.put("MYS", "Malaysia");
        COUNTRY_MAP.put("MDV", "Maldives");
        COUNTRY_MAP.put("MLI", "Mali");
        COUNTRY_MAP.put("MLT", "Malta");
        COUNTRY_MAP.put("MHL", "Marshall Islands");
        COUNTRY_MAP.put("MRT", "Mauritania");
        COUNTRY_MAP.put("MUS", "Mauritius");
        COUNTRY_MAP.put("MEX", "Mexico");
        COUNTRY_MAP.put("FSM", "Micronesia");
        COUNTRY_MAP.put("MDA", "Moldova");
        COUNTRY_MAP.put("MCO", "Monaco");
        COUNTRY_MAP.put("MNG", "Mongolia");
        COUNTRY_MAP.put("MNE", "Montenegro");
        COUNTRY_MAP.put("MAR", "Morocco");
        COUNTRY_MAP.put("MOZ", "Mozambique");
        COUNTRY_MAP.put("MMR", "Myanmar");
        COUNTRY_MAP.put("NAM", "Namibia");
        COUNTRY_MAP.put("NRU", "Nauru");
        COUNTRY_MAP.put("NPL", "Nepal");
        COUNTRY_MAP.put("NLD", "Netherlands");
        COUNTRY_MAP.put("NZL", "New Zealand");
        COUNTRY_MAP.put("NIC", "Nicaragua");
        COUNTRY_MAP.put("NER", "Niger");
        COUNTRY_MAP.put("NGA", "Nigeria");
        COUNTRY_MAP.put("MKD", "North Macedonia");
        COUNTRY_MAP.put("NOR", "Norway");
        COUNTRY_MAP.put("OMN", "Oman");
        COUNTRY_MAP.put("PAK", "Pakistan");
        COUNTRY_MAP.put("PLW", "Palau");
        COUNTRY_MAP.put("PAN", "Panama");
        COUNTRY_MAP.put("PNG", "Papua New Guinea");
        COUNTRY_MAP.put("PRY", "Paraguay");
        COUNTRY_MAP.put("PER", "Peru");
        COUNTRY_MAP.put("PHL", "Philippines");
        COUNTRY_MAP.put("POL", "Poland");
        COUNTRY_MAP.put("PRT", "Portugal");
        COUNTRY_MAP.put("QAT", "Qatar");
        COUNTRY_MAP.put("ROU", "Romania");
        COUNTRY_MAP.put("RUS", "Russia");
        COUNTRY_MAP.put("RWA", "Rwanda");
        COUNTRY_MAP.put("KNA", "Saint Kitts and Nevis");
        COUNTRY_MAP.put("LCA", "Saint Lucia");
        COUNTRY_MAP.put("VCT", "Saint Vincent and the Grenadines");
        COUNTRY_MAP.put("WSM", "Samoa");
        COUNTRY_MAP.put("SMR", "San Marino");
        COUNTRY_MAP.put("STP", "Sao Tome and Principe");
        COUNTRY_MAP.put("SAU", "Saudi Arabia");
        COUNTRY_MAP.put("SEN", "Senegal");
        COUNTRY_MAP.put("SRB", "Serbia");
        COUNTRY_MAP.put("SYC", "Seychelles");
        COUNTRY_MAP.put("SLE", "Sierra Leone");
        COUNTRY_MAP.put("SGP", "Singapore");
        COUNTRY_MAP.put("SVK", "Slovakia");
        COUNTRY_MAP.put("SVN", "Slovenia");
        COUNTRY_MAP.put("SLB", "Solomon Islands");
        COUNTRY_MAP.put("SOM", "Somalia");
        COUNTRY_MAP.put("ZAF", "South Africa");
        COUNTRY_MAP.put("SSD", "South Sudan");
        COUNTRY_MAP.put("ESP", "Spain");
        COUNTRY_MAP.put("LKA", "Sri Lanka");
        COUNTRY_MAP.put("SDN", "Sudan");
        COUNTRY_MAP.put("SUR", "Suriname");
        COUNTRY_MAP.put("SWE", "Sweden");
        COUNTRY_MAP.put("CHE", "Switzerland");
        COUNTRY_MAP.put("SYR", "Syria");
        COUNTRY_MAP.put("TWN", "Taiwan");
        COUNTRY_MAP.put("TJK", "Tajikistan");
        COUNTRY_MAP.put("TZA", "Tanzania");
        COUNTRY_MAP.put("THA", "Thailand");
        COUNTRY_MAP.put("TLS", "Timor-Leste");
        COUNTRY_MAP.put("TGO", "Togo");
        COUNTRY_MAP.put("TON", "Tonga");
        COUNTRY_MAP.put("TTO", "Trinidad and Tobago");
        COUNTRY_MAP.put("TUN", "Tunisia");
        COUNTRY_MAP.put("TUR", "Turkey");
        COUNTRY_MAP.put("TKM", "Turkmenistan");
        COUNTRY_MAP.put("TUV", "Tuvalu");
        COUNTRY_MAP.put("UGA", "Uganda");
        COUNTRY_MAP.put("UKR", "Ukraine");
        COUNTRY_MAP.put("ARE", "United Arab Emirates");
        COUNTRY_MAP.put("GBR", "United Kingdom");
        COUNTRY_MAP.put("USA", "United States");
        COUNTRY_MAP.put("URY", "Uruguay");
        COUNTRY_MAP.put("UZB", "Uzbekistan");
        COUNTRY_MAP.put("VUT", "Vanuatu");
        COUNTRY_MAP.put("VAT", "Vatican City");
        COUNTRY_MAP.put("VEN", "Venezuela");
        COUNTRY_MAP.put("VNM", "Vietnam");
        COUNTRY_MAP.put("YEM", "Yemen");
        COUNTRY_MAP.put("ZMB", "Zambia");
        COUNTRY_MAP.put("ZWE", "Zimbabwe");
    }

    public String getFullName(String code) {
        return COUNTRY_MAP.getOrDefault(code.toUpperCase(), "Unknown");
    }
}