ALTER TABLE user_premium
    ADD COLUMN IF NOT EXISTS price DECIMAL(10, 2) NOT NULL,
    ADD COLUMN IF NOT EXISTS currency VARCHAR(255) NOT NULL,
    ADD COLUMN IF NOT EXISTS premium_period VARCHAR(255) NOT NULL;