name: CI Pipeline User Service Triton Stream 10

on:
  pull_request:
    branches:
      ["triton-master-stream10"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: 17

      # Optional cache setup (improves performance)
      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build with Gradle
        run: 
          ./gradlew clean compileJava --stacktrace --no-daemon
          ./gradlew build --no-daemon --stacktrace --info
